<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Authors>Hoobi</Authors>
    <Product>Steward</Product>
    <Company>Hoobi</Company>
    <Copyright>Copyright (c) Hoobi $([System.DateTime]::Now.Year)</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)version.txt').Trim())</Version>
  </PropertyGroup>

</Project>
